WebDotNetMentoringProgram/Models/CustomErrorViewModel.cs
namespace WebDotNetMentoringProgram.Models
{
    public class CustomErrorViewModel
    {
        public string? RequestId { get; set; }

        public Exception? ThrownException { get; set; }
    }
}

WebDotNetMentoringProgram/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Mvc;
using WebDotNetMentoringProgram.Abstractions;
using WebDotNetMentoringProgram.Filters;
using WebDotNetMentoringProgram.Models;
using WebDotNetMentoringProgram.ViewModels;

namespace WebDotNetMentoringProgram.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;

        public CategoriesController(ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository ?? throw new ArgumentNullException(nameof(categoryRepository));
        }

        // GET: Categories
        [ApiExplorerSettings(IgnoreApi = true)]
        [ServiceFilter(typeof(LoggingResponseHeaderFilterService))]
        public IActionResult Index()
        {
            var _categories = _categoryRepository.GetCategories();

            var _categoryViewModel = (from _category in _categories
                select CategoryToCategoryViewModel(_category)).ToList();

            return View(_categoryViewModel);
        }

        [Route("Images/{id?}")]
        [Route("Categories/Image/{id?}")]
        [ApiExplorerSettings(IgnoreApi = true)]
        [ServiceFilter(typeof(LoggingResponseHeaderFilterService))]
        public IActionResult Image(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var _categories = _categoryRepository.GetCategories();

            var _categoryPicture = (from _category in _categories
                                    where _category.CategoryId == id
                                    select _category.Picture).FirstOrDefault();

            _categoryPicture = RemoveGarbageBytes(_categoryPicture);
            string imageBase64String = GetImageBase64String(_categoryPicture);

            ViewBag.Id = id;
            ViewBag.Image = imageBase64String;

            var image = ByteArrayToImage(_categoryPicture);
            return File(_categoryPicture, "image/bmp");
        }

        [Route("Categories/ChangeImage/{id?}")]
        [ApiExplorerSettings(IgnoreApi = true)]
        [ServiceFilter(typeof(LoggingResponseHeaderFilterService))]
        public IActionResult ChangeImage(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var _categories = _categoryRepository.GetCategories();

            var _categoryPicture = (from _category in _categories
                                    where _category.CategoryId == id
                                        select _category.Picture).FirstOrDefault();

            _categoryPicture = RemoveGarbageBytes(_categoryPicture);
            string imageBase64String = GetImageBase64String(_categoryPicture);

            ViewBag.Id = id;
            ViewBag.Image = imageBase64String;

            return View();
        }

        [Route("Categories/Image/{id?}")]
        [HttpPost, ActionName("NewImage")]
        [ApiExplorerSettings(IgnoreApi = true)]
        [ServiceFilter(typeof(LoggingResponseHeaderFilterService))]
        public IActionResult NewImage(int? id, ImageFileUpload imageFileUpload)
        {
            if (id == null)
            {
                return BadRequest();
            }

            if ((imageFileUpload == null) || (imageFileUpload.ImageFile == null))
            {
                return Problem($"Entity set {nameof(ImageFileUpload)} or {nameof(ImageFileUpload.ImageFile)} is null.");
            }

            var imageFile = imageFileUpload.ImageFile;

            //Getting file meta data
            var fileName = Path.GetFullPath(imageFile.FileName);
            var contentType = imageFile.ContentType;

            var _categories = _categoryRepository.GetCategories();

            var _categoryToUpdate = (from _category in _categories
                                        where _category.CategoryId == id
                                        select _category).FirstOrDefault();

            byte[] bitmapImage;
            using (var ms = new MemoryStream())
            {
                imageFile.CopyTo(ms);
                ms.Position = 0;
                bitmapImage = ms.ToArray();
            }

            _categoryToUpdate.Picture = bitmapImage;
            _categoryRepository.UpdateCategoryById(_categoryToUpdate);

            string imageBase64String = GetImageBase64String(bitmapImage);

            ViewBag.Id = id;
            ViewBag.Image = imageBase64String;

            return View();
        }

        private CategoryViewModel CategoryToCategoryViewModel(Category category)
        {
            CategoryViewModel categoryViewModel = new CategoryViewModel();

            categoryViewModel.CategoryId = category.CategoryId;
            categoryViewModel.CategoryName = category.CategoryName;
            categoryViewModel.Description = category.Description;
            categoryViewModel.Image = GetImageBase64String(category.Picture);

            return categoryViewModel;
        }

        private byte[] RemoveGarbageBytes(byte[] bytes)
        {
            // the original Northwind database images have 10746 bytes
            return (bytes != null && bytes.Length == 10746)
                ? bytes.Skip(78).ToArray()
                : bytes;
        }

        private string GetImageBase64String(byte[] categoryPicture)
        {
            return Convert.ToBase64String(categoryPicture).ToString();
        }

        private Image ByteArrayToImage(byte[] bytes)
        {
            using (MemoryStream stream = new MemoryStream(bytes))
            {
                using (Image img = SixLabors.ImageSharp.Image.Load(stream))
                {
                    return img;
                }
            }
        }
    }
}

WebDotNetMentoringProgram/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using WebDotNetMentoringProgram.Abstractions;
using WebDotNetMentoringProgram.Filters;
using WebDotNetMentoringProgram.Models;
using WebDotNetMentoringProgram.ViewModels;

namespace WebDotNetMentoringProgram.Controllers
{
    public class ProductsController : Controller
    {
        // should be private readonly
        private readonly IProductRepository _productRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly ISupplierRepository _supplierRepository;

        public ProductsController(IProductRepository productRepository, ICategoryRepository categoryRepository, ISupplierRepository supplierRepository)
        {
            _productRepository = productRepository ?? throw new ArgumentNullException(nameof(productRepository));
            _categoryRepository = categoryRepository ?? throw new ArgumentNullException(nameof(categoryRepository));
            _supplierRepository = supplierRepository ?? throw new ArgumentNullException(nameof(supplierRepository));
        }

        // GET: Products
        [ServiceFilter(typeof(LoggingResponseHeaderFilterService))]
        public IActionResult Index(int _numberOfProductsToShow = 10)
        {
            if (_numberOfProductsToShow == 0)
                _numberOfProductsToShow = _productRepository.GetProductCount();

            var _productTableViewModel = new List<ProductTableViewModel>();

            var _productsToShow = _productRepository.GetProductsWithLimit(_numberOfProductsToShow);

            foreach (var product in _productsToShow)
            {
                _productTableViewModel.Add(CreateProductTableViewModelFromProduct(product));
            }

            return View(_productTableViewModel);
        }

        // GET: Products/Details/5
        [ServiceFilter(typeof(LoggingResponseHeaderFilterService))]
        public IActionResult Details(int? id)
        {
            // if we don't have any await operation in method body we don't need to use async Task
            if (id == null)
            {
                return BadRequest();
            }

            var product = _productRepository.GetProductById(id);

            if (product == null)
            {
                return NotFound();
            }

            var productTableView = CreateProductTableViewModelFromProduct(product);

            return View(productTableView);
        }

        // GET: Products/Create
        [ServiceFilter(typeof(LoggingResponseHeaderFilterService))]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ServiceFilter(typeof(LoggingResponseHeaderFilterService))]
        public IActionResult Create([Bind("ProductID,ProductName,SupplierID,CategoryId,QuantityPerUnit,UnitPrice,UnitsInStock,UnitsOnOrder,ReorderLevel,Discontinued")] Product product)
        {
            if (ModelState.IsValid)
            {
                _productRepository.Add(product);
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Edit/5
        [ServiceFilter(typeof(LoggingResponseHeaderFilterService))]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var _product = _productRepository.GetProductById(id);

            if (_product == null)
            {
                return NotFound();
            }

            var _productTableViewModel = CreateProductTableViewModelFromProduct(_product);

            // SupplierList List<SelectListItem>
            ViewBag.CompanyNames = _supplierRepository.GetSupplierNames();

            // CategoryList List<SelectListItem>
            ViewBag.CategoryNames = _categoryRepository.GetCategoryNames();

            return View(_productTableViewModel);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ServiceFilter(typeof(LoggingResponseHeaderFilterService))]
        public IActionResult Edit(int? id, IProductTableViewModel productTableViewModel)
        {
            if (id != productTableViewModel.ProductID)
            {
                return BadRequest();
            }

            if (ModelState.IsValid)
            {
                var product = CreateProductFromProductTableViewModel(productTableViewModel);

                _productRepository.Update(product);
                return RedirectToAction(nameof(Index));
            }

            return View(productTableViewModel);
        }

        // GET: Products/Delete/5
        [ServiceFilter(typeof(LoggingResponseHeaderFilterService))]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var product = _productRepository.GetProductById(id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [ServiceFilter(typeof(LoggingResponseHeaderFilterService))]
        public IActionResult DeleteConfirmed(int? id)
        {
            // please keep the same behaviour for all endpoint actions 
            // one you check id and whole context here only context
            if (id == null)
            {
                return BadRequest();
            }

            var product = _productRepository.GetProductById(id);
            if (product != null)
            {
                _productRepository.Remove(product);
            }
            
            return RedirectToAction(nameof(Index));
        }

        private ProductTableViewModel CreateProductTableViewModelFromProduct(Product product)
        {
            var supplierSelected = _supplierRepository.GetSupplierById(product.ProductID);
            var categorySelected = _categoryRepository.GetCategoryById(product.CategoryID);

            return new ProductTableViewModel()
            {
                ProductID = product.ProductID,
                ProductName = product.ProductName,
                CompanyName = supplierSelected.CompanyName,
                CategoryName = categorySelected.CategoryName,
                QuantityPerUnit = product.QuantityPerUnit,
                UnitPrice = product.UnitPrice,
                UnitsInStock = product.UnitsInStock,
                UnitsOnOrder = product.UnitsOnOrder,
                ReorderLevel = product.ReorderLevel,
                Discontinued = product.Discontinued
            };
        }

        private Product CreateProductFromProductTableViewModel(IProductTableViewModel productTableViewModel)
        {
            var supplierSelected = _supplierRepository.GetSupplierByName(productTableViewModel.CompanyName);
            var categorySelected = _categoryRepository.GetCategoryByName(productTableViewModel.CategoryName);

            return new Product(
                productTableViewModel.ProductID,
                productTableViewModel.ProductName,
                supplierSelected.SupplierID,
                categorySelected.CategoryId,
                productTableViewModel.QuantityPerUnit,
                productTableViewModel.UnitPrice,
                productTableViewModel.UnitsInStock,
                productTableViewModel.UnitsOnOrder,
                productTableViewModel.ReorderLevel,
                productTableViewModel.Discontinued
                ) {};
        }
    }
}

WebDotNetMentoringProgram/Controllers/SuppliersController.cs
using Microsoft.AspNetCore.Mvc;
using WebDotNetMentoringProgram.Abstractions;
using WebDotNetMentoringProgram.Filters;
using WebDotNetMentoringProgram.Repositories;

namespace WebDotNetMentoringProgram.Controllers
{

    public class SuppliersController : Controller
    {
        private readonly ISupplierRepository _supplierRepository;

        public SuppliersController(ISupplierRepository supplierRepository)
        {
            _supplierRepository = supplierRepository ?? throw new ArgumentNullException(nameof(supplierRepository));
        }

        // GET: Suppliers
        [ServiceFilter(typeof(LoggingResponseHeaderFilterService))]
        public IActionResult Index()
        {
            // tenatary condition will be look better
            return (_supplierRepository != null)
                ? View(_supplierRepository.GetSuppliers())
                : Problem($"Entity set '{nameof(SupplierRepository)}' is null.");
        }
    }
}

WebDotNetMentoringProgram/Views/Shared/CustomError.cshtml
@model CustomErrorViewModel
@{
    ViewData["Title"] = "CustomError";
}

<h1 class="text-danger">Error.</h1>
<h2 class="text-danger">An error occurred while processing your request. You may find the error details at the <strong>log file</strong> at <strong>@DateTime.Now.ToLongTimeString() ERR</strong>.</h2>

    <p>
        <strong>Request ID:</strong> <code>@Model.RequestId</code>
    </p>

WebDotNetMentoringProgram/Views/Shared/_HomeLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebDotNetMentoringProgram</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/js/bootstrap.min.js" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

    @await Component.InvokeAsync("BreadCrumb")

    <br>

    <partial name="_LoginPartial" />

    <div class="text-center">
        <h1 class="display-4">Welcome on Web .NET Mentoring Program #10</h1>
    </div>

    <div class="container align-content-center">
        <div class="row">
            <div class="col-md-3 col-sm-4 col-lg">
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
            </div>
            <div class="col-md-3 col-sm-4 col-lg">
                <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
            </div>
            <div class="col-md-3 col-sm-4 col-lg">
                <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
            </div>
            <div class="col-md-3 col-sm-4 col-lg">
                <a class="nav-link text-dark" asp-area="" asp-controller="Suppliers" asp-action="Index">Suppliers</a>
            </div>
            <div class="col-md-3 col-sm-4 col-lg">
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div id="imageCarousel" class="carousel slide" data-interval="3000" data-ride="carousel">
                    <div class="carousel-inner">
                        <div class="item active">
                            <img src="~/images/boat.jpg" class="img-responsive" />
                        </div>
                        <div class="item">
                            <img src="~/images/house.jpg" class="img-responsive" />
                        </div>
                        <div class="item">
                            <img src="~/images/coffee.jpg" class="img-responsive" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <main role="main" class="pb-3">
           @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebDotNetMentoringProgram/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebDotNetMentoringProgram</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>

    @if (IsSectionDefined("header"))
    {
        @RenderSection("header")
    }
    else
    {
        <header>
            <nav class="navbar navbar-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebDotNetMentoringProgram</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-xlg-inline-flex justify-content-end">
                        <ul class="navbar-nav flex-grow-1 justify-content-end">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Suppliers" asp-action="Index">Suppliers</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
    }

    @await Component.InvokeAsync("BreadCrumb")

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @if (IsSectionDefined("footer"))
    {
        @RenderSection("footer")
    }
    else
    {
        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2023 - WebDotNetMentoringProgram - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>       
    }

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>